#! /bin/sh
### BEGIN INIT INFO
# Provides:          li-metrics-agent
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Start Server Metrics
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin
PYTHON=$(which python)
DESC="Load Impact Server Metrics Agent"
NAME=li-metrics-agent
DAEMON=/usr/lib/${NAME}/${NAME}.py
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
CONFFILE=/etc/$NAME/$NAME.conf

. /lib/init/vars.sh
. /lib/lsb/init-functions

check_start() {
  [ -x $CONFFILE ] || (echo "Please configure ${NAME}, See: ${CONFFILE}" && exit 1)
}

case "$1" in
    start)
        check_start
        log_daemon_msg "Starting $DESC" "$NAME"
        start-stop-daemon --start --quiet --pidfile "$PIDFILE" \
                --exec "$PYTHON $DAEMON" --oknodo -- $DAEMON_ARGS
        log_end_msg $?
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        start-stop-daemon --stop --quiet --pidfile "$PIDFILE" \
                --retry 1 --oknodo
        log_end_msg $?
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
