#!/bin/sh

# If symlink does not exist, create it
[ -h /etc/rc2.d/S99li_metrics_agent ] || ln -s /etc/init.d/li_metrics_agent /etc/rc2.d/S99li_metrics_agent

CONF_FILE=/etc/li_metrics_agent/li_metrics_agent.conf
SAMPLE_CONF_FILE=/etc/li_metrics_agent/li_metrics_agent.conf.sample
AGENT_NAME=`hostname`
TOKEN=""
HAS_AGENT_NAME_CONF="no"
HAS_TOKEN_CONF="no"

if [ -f ${CONF_FILE} ]; then
  if grep "^agent_name" ${CONF_FILE} >/dev/null ; then
    AGENT_NAME=`grep "^agent_name" ${CONF_FILE} |awk -F\= '{print $2}' |awk '{print $1}'`
    HAS_AGENT_NAME_CONF="yes"
  fi
  if grep "^server_metrics_token" ${CONF_FILE} >/dev/null ; then
    TOKEN=`grep "^server_metrics_token" ${CONF_FILE} |awk -F\= '{print $2}' |awk '{print $1}'`
    HAS_TOKEN_CONF="yes"
  fi
fi

/bin/echo ""
/bin/echo "--- AGENT NAME ---"
/bin/echo "You have to enter a unique name identifying this agent. This name will be"
/bin/echo "displayed in the Load Impact user interface, and allow you to enable/disable"
/bin/echo "server metrics data collection for this particular host."
/bin/echo ""

while true 
do
  /bin/echo "Current name for this agent is: ${AGENT_NAME}"
  /bin/echo -n "Do you want to change the name? (y/N): "
  read ans
  if [ "${ans}x" = "yx" ]; then
    /bin/echo -n "Enter new agent name: "
    read AGENT_NAME
    /bin/echo ""
  else
    break
  fi
done

/bin/echo ""
/bin/echo "--- SERVER METRICS TOKEN ---"
/bin/echo "You also have to tell this agent what your Load Impact server metrics token is."
/bin/echo "The token is a secret hash that the agent sends together with measurement data"
/bin/echo "to Load Impact, to authenticate itself as a legitimate agent. If you do not "
/bin/echo "enter a token, or enter the wrong token, your agent will not be able to send"
/bin/echo "any data to Load Impact."
/bin/echo ""
/bin/echo "You can find out what your token is by visiting https://loadimpact.com/account/"
/bin/echo ""

while true 
do
  if [ "${TOKEN}x" = "x" ]; then
    /bin/echo "Current token is: [none]"
    ans="y"
  else
    /bin/echo "Current token is: ${TOKEN}"
    /bin/echo -n "Do you want to change the token string? (y/N): "
    read ans
  fi
  if [ "${ans}x" = "yx" ]; then
    /bin/echo -n "Enter token string: "
    read TOKEN
    /bin/echo ""
  else
    break
  fi
done


TMPFILE=/tmp/li_metrics_agent.conf
[ -f ${CONF_FILE} ] && cp -f ${CONF_FILE} ${CONF_FILE}.bak

if [ "${HAS_AGENT_NAME_CONF}" = "yes" ]; then
  sed 's/^agent_name.*/agent_name \= '"${AGENT_NAME}/" ${CONF_FILE} >${TMPFILE}
else
  sed 's/^agent_name.*/agent_name \= '"${AGENT_NAME}/" ${SAMPLE_CONF_FILE} >${TMPFILE}
fi

sed 's/^server_metrics_token.*/server_metrics_token \= '"${TOKEN}/" ${TMPFILE} >${CONF_FILE}

# Create symlink to config file, if it does not already exist
[ -h /usr/lib/li_metrics_agent/li_metrics_agent.conf ] || ln -s ${CONF_FILE} /usr/lib/li_metrics_agent/li_metrics_agent.conf

/etc/init.d/li_metrics_agent stop
/etc/init.d/li_metrics_agent start

